services:
  postgres:
    image: 'postgres:18-alpine3.23'
    environment:
      - 'POSTGRES_DB=kairosdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:4.2.5-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - '5672:5672'
  redis:
    image: 'redis:8.6-alpine'
    ports:
      - '6379:6379'
